### ISSUE TITLE
Missing script files for obtaining concept node and concept pairs citation data

### ISSUE THREAD

**Issue by zzg-971030** [artificial-scientist-lab/Impact4Cast#1]
Dear Mario Krenn,

I hope this message finds you well. I've been thoroughly enjoying your GitHub repository and the work you've done on predicting scientific concept influence, which is truly impressive. Your paper has been incredibly insightful, and I'm particularly interested in replicating and extending your analysis.

However, I noticed that the repository does not include the code used to generate the **_concept_node_citation_data_year?.parquet_** and **_concept_pair_citation_data_year?.parquet_** files. These files seem crucial for the analysis and I am wondering if you could kindly share the scripts or notebooks used to create them.

I understand that your time is valuable, and I appreciate any help you can offer. Thank you very much for your time and for sharing your work. I'm looking forward to hearing back from you. If you would prefer not to publicly upload the code but are willing to share it directly with the individual, you can also send it to my email, 1558186999@qq.com.

Best regards,

Zhengang Zhang
School of Information and Safety Engineering,
Zhongnan University of Economics and Law
Cell: +86-1785 3146 087

**Comment by XuemeiGu** [comment]
Thank you for your interest in our work. To generate the `concept_node_citation_data_year?.parquet` files, you can simply use the data downloaded via [zenodo.org](https://zenodo.org/records/10692137). The process includes summing and averaging the relevant rows for metrics such as yearly citations or total citations since publication for each node or concept up to the specified year.

For your convenience, I have uploaded the script to GitHub and will also send the files to you via email. Feel free to reach out if you have any problems with the code or data.

**Comment by zzg-971030** [comment]
Thank you very much for your detailed guidance and assistance! I have successfully downloaded the required data from zenodo.org, and also received the script you uploaded to GitHub along with the files sent via email. This is invaluable for my ongoing work. Your prompt response and thoughtful help are truly appreciated.
